### ISSUE TITLE
Unable to refresh page using CTRL + R

### ISSUE THREAD

**Issue by alexjlockwood** [romannurik/AndroidIconAnimator#108]
I wasn't sure if this was intentional or not.

On one hand you likely wouldn't ever want to refresh the screen (unless you wanted a quick and easy way to restart the app).

On the other, you'd get the `beforeonload` dialog if you attempted to refresh the page anyway, so... dunno.

Thought it was worth pointing out.

**Comment by romannurik** [comment]
Yeah I trap the R key for "reverse". My guess is only we would encounter this during active development. You rarely if ever want to refresh in prod IMO..
