### ISSUE TITLE
Use fill color of #000 by default when neither fill nor stroke are specified on path node

### ISSUE THREAD

**Issue by alexjlockwood** [romannurik/AndroidIconAnimator#111]
While Android seems to draw nothing to the display when fill/stroke colors are not specified on a `VectorDrawable`, it seems like Chrome and FireFox use a fill color of `#000` when neither fill nor stroke are specified on a path node. Using this seems like a better alternative than drawing nothing. Then again, I suppose the user could just change the color in the property inspector too.

**Comment by romannurik** [comment]
We should just do this on SVG import.. I'd avoid changing defaults at this point otherwise..

**Comment by alexjlockwood** [comment]
Yeah, agree.

However, one thing to keep in mind is that not having a fill/stroke specified doesn't necessarily mean its color should be black (because it is possible the path is inheriting a fill/stroke color from a parent node instead). Maybe that can be fixed later though.
