### ISSUE TITLE
Convert all paths to relative or absolute

### ISSUE THREAD

**Issue by BraisGabin** [romannurik/AndroidIconAnimator#136]
It'll be really handy to export all the paths using relative commands (or absolute).

Android doesn't know how to morph these two paths:

```
M10 10  L10 20  L20 10  Z
M10 10  l10  0  l 0 10  z
```

Android fails at runtime. Do something like this would be really aprecieated: http://stackoverflow.com/a/23716756/842697

**Comment by alexjlockwood** [comment]
I suggest you use https://shapeshifter.design to make the paths morphable with each other.

We have plans to at some point merge the features of AndroidIconAnimator and ShapeShifter into one. That should solve this problem.

**Comment by BraisGabin** [comment]
That would be great! Because there are problems morphing between `c` and `s` too.

**Comment by alexjlockwood** [comment]
Shape Shifter solves that too. Android Icon Animator pretty much assumes the paths you enter are compatible right now.
