### ISSUE TITLE
Add ability to set/animate the <vector> tag's android:alpha property

### ISSUE THREAD

**Issue by alexjlockwood** [romannurik/AndroidIconAnimator#32]
It is possible to animate the entire vector's opacity by animating the `<vector>` tag's `android:alpha` property. AndroidIconAnimator doesn't yet support setting or animating this property.

[Here is an example AVD](https://github.com/alexjlockwood/adp-delightful-details/blob/master/app/src/main/res/drawable/avd_trimclip_flashlight_enabled_to_disabled.xml) that animates this property.

**Comment by romannurik** [comment]
Hm, are there legit use-cases for this? I don't think it's a huge change, but feels a little odd.

**Comment by alexjlockwood** [comment]
The System UI quick setting tiles use it a bunch:

![Example animated vector drawables](http://i.imgur.com/0aFdjJn.gif)

You can see the property being animated in the airplane and flashlight icons. It's useful in cases where you want to apply a single alpha value on the entire drawable (rather than on each individual path, which won't look the same if two translucent paths overlap each other). I assume it is also a setting in After Effects, because Ari's thing seems to support this attribute as well.

**Comment by alexjlockwood** [comment]
Also, even if no translucent paths overlap each other, using this property still might be useful because modifying the colors of the paths themselves will alter the behavior of whatever tintMode is currently set on the drawable I think (since the tint will only be applied to the completely opaque path pixels).
