### ISSUE TITLE
Animate between the 'play/pause' icon using a path morph animation when the user clicks the button

### ISSUE THREAD

**Issue by alexjlockwood** [romannurik/AndroidIconAnimator#39]
...because I feel like it would be a crime not to. :)

**Comment by romannurik** [comment]
Ha! Possibly. Want to think about the best way to do this first.

**Comment by alexjlockwood** [comment]
Yeah... right now the only way to path morph SVGs is to either (1) use SMIL, (2) use some third party library like GreenSock or Snap.svg, or (3) reuse the animation loop you've already written to render the canvas artwork somehow. (1) isn't ideal because SMIL is going to be removed from browsers eventually (although Chrome has promised to provide a polyfill when that happens at least), (2) is meh, and (3) I'm guessing is possible but dunno how reusable your current code is in order to make that happen yet.

Obviously I didn't mean to imply this should be a high priority bug or anything. :D

**Comment by romannurik** [comment]
I'm thinking to use a library I'm writing on the side for this, or just an
SVG sprite sheet

**Comment by romannurik** [comment]
Waiting on publishing a library for PNG/SVG sprites.

**Comment by alexjlockwood** [comment]
Yo... I want to make an option to export animations for the web in my path morphing tool. Should I wait on your library as well? :)

**Comment by alexjlockwood** [comment]
A related question... do you think AndroidIconAnimator will ever support exporting to a web-based format? (or iOS)

**Comment by romannurik** [comment]
Yeah I'd like to add PNG sprite export soon which will work for both
platforms.

**Comment by alexjlockwood** [comment]
Hmm... kk. Then for my path morphing tool I'm gonna get the export to AVD stuff worked out and then eventually I can hopefully use whatever you're making somehow for web/ios. :D

**Comment by romannurik** [comment]
Ended up not needing any JS, so no need for a library.
