### ISSUE TITLE
New trim path code breaks back_simple.iconanim

### ISSUE THREAD

**Issue by romannurik** [romannurik/AndroidIconAnimator#67]
The trim path code (without the epsilon) breaks `test_simple_back.iconanim` in the examples directory.

/cc @alexjlockwood

**Comment by alexjlockwood** [comment]
I don't see a file named `test_simple_back.iconanim` anywhere... you sure you got the name right?

**Comment by romannurik** [comment]
Oops, it's https://github.com/romannurik/AndroidIconAnimator/blob/master/examples/back_simple.iconanim

**Comment by alexjlockwood** [comment]
This is fixed now.
