### ISSUE TITLE
Investigate increasing the max viewport width/height to a value larger than 1024

### ISSUE THREAD

**Issue by alexjlockwood** [romannurik/AndroidIconAnimator#77]
I've been gathering SVGs from UX teams and so far two different teams have sent me SVGs that use a viewport size that is 1920x1080... so if it isn't too difficult to make this value larger that would probably be helpful.

**Comment by romannurik** [comment]
The tool isn't really built for dealing with such large sizes (particularly since you can't really zoom in or pan the canvas yet.. see #20). Having said that, I don't see a problem of upping from 1024 to something slightly larger...

**Comment by alexjlockwood** [comment]
BTW, I think the reason why this doesn't seem to work for large widths/height is because of this LOC in `canvas.js`:

    this.scale_ = Math.max(1, Math.floor(this.scale_));

When the vector drawable's width/height is larger than the number of pixels available to display the canvas, then the scale is set to 1 CSS pixel per vector drawable pixel and this causes the canvas to be drawn outside of the element's bounds. I based my project's canvas off of yours and was able to get it working better by removing the max/floor.

**Comment by romannurik** [comment]
While this was intentional (so that you always see it at 1:1), I do think it's time to rethink this. Thanks for bubbling it up!
