### ISSUE TITLE
Add option to clear all existing layers from canvas

### ISSUE THREAD

**Issue by alexjlockwood** [romannurik/AndroidIconAnimator#78]
Either that or maybe when importing an SVG, show the same dialog that is shown when the user drags and drops an SVG.

**Comment by romannurik** [comment]
This would be during import? File > New already clears your layers. We can add a separate option `Import > New file from SVG` that would sit alongside `Import > Add layers from SVG`

**Comment by alexjlockwood** [comment]
Yeah, either way. The main thing was just that there wasn't an easy way to import a second new SVG on top of an existing imported SVG. The only way to do that right now is by dragging and dropping an SVG file, which causes the "start from scratch" dialog to show.
