### ISSUE TITLE
Investigate possible bug in svgpathdata.js (transformPoint_ function)

### ISSUE THREAD

**Issue by alexjlockwood** [romannurik/AndroidIconAnimator#84]
There is a function called `transformPoint_` in `svgpathdata.js` that is declared as follows:

```
function transformPoint_(p, transformMatricies) {
  return transformMatricies.reduce((p, transform) => {
    const m = transform.matrix;
    return {
      // dot product
      x: m.a * p.x + m.c * p.y + m.e * 1,
      y: m.b * p.x + m.d * p.y + m.f * 1,
    };
  }, p);
}
```

This function basically applies a set of transform matrices using matrix multiplication.

However, I didn't quite understand the way this is meant to work. The transform matrix notation is traditionally:

```
[ a, b, e ]
[ c, d, f ]
[ 0, 0, 1 ]
```

And when multiplying this matrix by a point, you are doing:

```
[ x ]     [ a, b, e ]     [ ax + by + e ]
[ y ]  *  [ c, d, f ]  =  [ cx + dy + f ]
[ 1 ]     [ 0, 0, 1 ]     [ 1           ]
```

So I'm unclear why `transformPoint_()` uses a different equation to calculate the dot product. Under the notation above, I would have expected the dot product to be calculated like this (i.e. swap the `m.b` and `m.c`):

```
x: m.a * p.x + m.b * p.y + m.e * 1,
y: m.c * p.x + m.d * p.y + m.f * 1,
```

It's possible there is no bug here at all but I wanted to flag it down just in case it was a subtle issue.

**Comment by romannurik** [comment]
The notation is actually:

```
a c e
b d f
0 0 1
```

So I think we should be OK..

**Comment by alexjlockwood** [comment]
omg... this is the reason why none of my code has been working. a;lsdjkf;ajksdf
