### ISSUE TITLE
Possible bug in svgpathdata.js

### ISSUE THREAD

**Issue by alexjlockwood** [romannurik/AndroidIconAnimator#91]
`svgpathdata.js` contains the following code (link below):

    if (rx == 0 || ry == 0) {
      // degenerate to line
      length += dist_(currentPointX, currentPointY, tempPoint1X, tempPoint1Y);
      expandBounds_(tempPoint1X, tempPoint1Y);
      return;
    }

I think you may have forgotten to set the current point equal to the next point for this case?

https://github.com/romannurik/AndroidIconAnimator/blob/master/app/scripts/svgpathdata.js#L613-L618

**Comment by romannurik** [comment]
Yep, looks like it!

**Comment by romannurik** [comment]
Fixed by #92
