### ISSUE TITLE
Question about use of trailing underscores to name variables

### ISSUE THREAD

**Issue by alexjlockwood** [romannurik/AndroidIconAnimator#93]
Sorry for submitting this as a bug... I would have labeled it as a question but not sure how to do that (or if I'm able to do that at all w/o being the project owner).

I've been wondering for a while how/when you add trailing underscores to variable names. Is that part of some google/js style guide or something?

**Comment by romannurik** [comment]
Just represents a private field/method. I think it's part of a standard Google style guide, I don't recall from where though.
