### ISSUE TITLE
Possible bug in computing path length/bounds in svgpathdata.js

### ISSUE THREAD

**Issue by alexjlockwood** [romannurik/AndroidIconAnimator#94]
Link here: https://github.com/romannurik/AndroidIconAnimator/blob/master/app/scripts/svgpathdata.js#L557

Consider the array of commands representing the SVG path `M 0 0 L 12 12 M 16 16 L 20 20 L 16 20 Z`.

The closepath command at the end should draw a line from (16,20) to (16,16) because (16,16) is the location of the last move command. The code linked above looks like it will draw a line from (16,20) to (0,0) instead.

I think the solution is to get rid of the condition `if (firstPoint)` checks in the move command case? A move command should always reset the first sub point point so that a subsequent close path command will know how to close the path.

**Comment by alexjlockwood** [comment]
I think there is also a bug on this line of code: https://github.com/romannurik/AndroidIconAnimator/blob/master/app/scripts/svgpathdata.js#L577

Consider the SVG: `M 0 0 L 12 12 M 16 16 L 20 20 L 16 20 Z L 12 16 L 12 20 Z`

The first close path command will draw a line correctly to `(16,16)`. However, the second close path command will do nothing because the first close path command reset the first point variable. The correct behavior is that it should draw a line from its current point to the location of the last move command (which is still `(16,16)` even after the first close path command).

**Comment by alexjlockwood** [comment]
A third bug I think is that the close path case should set the value of the `currentPoint` variable so that the next command begins at the correct location.

**Comment by romannurik** [comment]
Good catches, thanks! Unfortunately I think trim paths are kinda broken for multi-subpath paths :-/ And this really reinforces the need for good tests :-/
