### ISSUE TITLE
Confirm implementation of MathUtil.transformMatrix_ is correct

### ISSUE THREAD

**Issue by alexjlockwood** [romannurik/AndroidIconAnimator#96]
Your [source code](https://github.com/romannurik/AndroidIconAnimator/blob/master/app/scripts/RenderUtil.js#L97-L104) looks like this:

```
function transformMatrix_(s, t) {
  return [
    s[0] * t[0] + s[1] * t[2],
    s[0] * t[1] + s[1] * t[3],
    t[0] * s[2] + t[2] * s[3],
    t[1] * s[2] + s[3] * t[3],
    t[0] * s[4] + t[4] + t[2] * s[5],
    t[1] * s[4] + t[3] * s[5] + t[5],
  ];
}
```

However, when I compute the dot product in [wolfram alpha](https://www.wolframalpha.com/input/?i=%7B%7Ba,c,e%7D,%7Bb,d,f%7D,%7B0,0,1%7D%7D+*+%7B%7Ba%27,c%27,e%27%7D,%7Bb%27,d%27,f%27%7D,%7B0,0,1%7D%7D), the first matrix slot is `s[0] * t[0] + s[2] * t[1]` instead of `s[0] * t[0] + s[1] * t[2]`.

Is it possible you mixed up the matrix array ordering?

**Comment by romannurik** [comment]
Nope, should be right. If it wasn't I think you'd see a ton of broken transform operations :)

[Wolfram alpha source](https://www.wolframalpha.com/input/?i=%7B%7Bs_0,s_2,s_4%7D,%7Bs_1,s_3,s_5%7D,%7B0,0,1%7D%7D+*+%7B%7Bt_0,t_2,t_4%7D,%7Bt_1,t_3,t_5%7D,%7B0,0,1%7D%7D)

![image](https://cloud.githubusercontent.com/assets/100155/22402102/238de686-e5b9-11e6-8025-2484a3288c8f.png)

**Comment by romannurik** [comment]
Whoa. Nevermind, you were right. Somehow things magically worked :-/

**Comment by alexjlockwood** [comment]
The typo wouldnt have affected scaling I think... So maybe you didn't test rotations or whatever when you made the change? Who knows :p

**Comment by romannurik** [comment]
Nah what happened was I had the order of operations reversed in the getMatrixForLayer routine, and pushed instead of unshifted child layers' transforms to the transform stack. Basically it all still worked great but the code was wrong :-) thanks for catching it.
